#!/bin/python

with open("example.cimg", "wb") as file:
    file.write(b"cIMG") 
    file.write((2).to_bytes(2, "little"))
    
    file.write((51).to_bytes(2, "little")) 
    file.write((20).to_bytes(2, "little")) 
    
    # Každý pixel: R (0x8C), G (0x1D), B (0x40), ASCII ('X')
    asu_maroon_r = 0x8C
    asu_maroon_g = 0x1D
    asu_maroon_b = 0x40
    
    for _ in range(51 * 20):
        file.write(bytes([asu_maroon_r, asu_maroon_g, asu_maroon_b, ord('X')]))
