#!/bin/python

with open("example.cimg", "wb") as file:
    file.write(b"cIMG")
    file.write((1).to_bytes(4, "little"))
    file.write((44).to_bytes(8, "little"))
    file.write((24).to_bytes(2, "little"))
    file.write((44*24)*b"x")
